### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by hxc74** [holocronweaver/deluge-ratio#1]
Text is inversed shoukd be total uploads / total downloads

**Comment by paol** [comment]
Yup, just installed this and it was the first thing I noticed :)

**Comment by holocronweaver** [comment]
I merged the associated pull request, so this should not be fixed. Sorry for the delay, I somehow didn't receive notifications for this project.

**Comment by cyanlink** [comment]
@holocronweaver hey bud I think you forgot to make a new release..?
